sudo: false
language: node_js
env:
  - APP_DIR=src
node_js:
  - 6
  - node
script:
  - npm install
  - npm run lint
  - npm test
deploy:
  provider: npm
  api_key: $NPM_TOKEN
  email: $NPM_EMAIL
  on:
    branch: master
notifications:
  email:
    on_success: never
    on_failure: always
